cmake_minimum_required(VERSION 2.8)

# json11 settings
include(ExternalProject)

set(JSON11_PROJECT_NAME json11)
set(JSON11_GIT_REPOSITORY https://github.com/ngc-developers/json11.git)
set(JSON11_GIT_TAG v1.1)

if(INSTALL_EXTERNAL_PROJECTS)
  if(NOT INSTALL_EXTERNAL_PROJECTS_PREFIX)
    set(INSTALL_EXTERNAL_PROJECTS_PREFIX ${CMAKE_INSTALL_PREFIX})
  endif()

  ExternalProject_Add(
    ${JSON11_PROJECT_NAME}
    GIT_REPOSITORY ${JSON11_GIT_REPOSITORY}
    GIT_TAG ${JSON11_GIT_TAG}
    PREFIX ${CMAKE_CURRENT_BINARY_DIR}/projects/${JSON11_PROJECT_NAME}
    CMAKE_ARGS -DCMAKE_INSTALL_PREFIX=${INSTALL_EXTERNAL_PROJECTS_PREFIX}
    LOG_DOWNLOAD ON
    )

  set(JSON11_INCLUDE_PATH ${CMAKE_INSTALL_PREFIX}/include)
  set(JSON11_LIBRARY ${CMAKE_INSTALL_PREFIX}/lib/libjson11.a)
else()
  ExternalProject_Add(
    ${JSON11_PROJECT_NAME}
    GIT_REPOSITORY ${JSON11_GIT_REPOSITORY}
    GIT_TAG ${JSON11_GIT_TAG}
    PREFIX ${CMAKE_CURRENT_BINARY_DIR}/projects/${JSON11_PROJECT_NAME}
    INSTALL_COMMAND ""
    LOG_DOWNLOAD ON
    )

  ExternalProject_Get_Property(${JSON11_PROJECT_NAME} source_dir)
  ExternalProject_Get_Property(${JSON11_PROJECT_NAME} binary_dir)

  set(JSON11_INCLUDE_PATH ${source_dir})

  add_library(JSON11_LIBRARY STATIC IMPORTED GLOBAL)
  set_property(
    TARGET JSON11_LIBRARY
    PROPERTY IMPORTED_LOCATION ${binary_dir}/libjson11.a
    )
endif()
